### ISSUE TITLE
Not Able to Run This Libaray in C#

### ISSUE THREAD

**Issue by sourabhlodha** [RNCryptor/RNCryptor-cs#12]
Hi Team,

I am not able to run this library in c#.

Can you please provide me with the solution.

Thanks

**Comment by rnapier** [comment]
I don’t know what this means. What code did you write and what messages do you receive?

**Comment by sourabhlodha** [comment]
@rnapier I am using the sample which is written in c# by RNCryptor but doesn't able to find the RNcrypto.dll file in bin folder can you help me out with that.

**Comment by rnapier** [comment]
I don't understand what you mean by "the sample."

What code did you write, how did you compile it, and what messages do you receive? Please list the exact steps you took and the exact error messages it generated.

**Comment by sourabhlodha** [comment]
I Download the RNCryptor and open the solution file in visual studio.
I call the function of Decrypt from decryption file and Run the file.
While compile it shows me the error that RNCryptor.dll is not found in Bin folder.
I am running on Windows10.

Can you guide me steps how to run the RNCryptor in visual studio?

**Comment by rnapier** [comment]
See the latest commit which includes an `rncrypt` example project to get you started.
