### ISSUE TITLE
Encrypt string

### ISSUE THREAD

**Issue by Sub-Zero-1** [RNCryptor/RNCryptor-cs#13]
Hi,

can somebody give me an example of how to just simply encrypt a string?!
As I see the code has changed into byte[] instead of passing a string. I tried severel things but does not work for me.

**Comment by rnapier** [comment]
Assuming you want the string encoded as UTF-8:

    byte[] bytes = System.Text.Encoding.UTF8.GetBytes(string);

**Comment by Sub-Zero-1** [comment]
Sorry, but that example is not what is an example:
This is an example which is working!:

Encryption:

            var plaintext = "thisismyplaintext";
            var password= "mypassword";
            var encryptor = new Encryptor();
            byte[] baText = Encoding.UTF8.GetBytes(plaintext);
            var encrypted = encryptor.Encrypt(baText, mykey);
            string result = Convert.ToBase64String(encrypted);

Decryption:

            var decryptor = new Decryptor();
            var password= "mypassword";
            string encyptedstring = "xyz1234abcdefghijklmn";
            var decrypted = decryptor.Decrypt(Convert.FromBase64String(encryptedstring), password);
            string result = Encoding.UTF8.GetString(decrypted);

The more, this can be used to encrypt/decrypt strings which where encrypted/decrypted by another implementation like I do on Swift3 or Android (JNCryptor).

**Comment by rnapier** [comment]
The conversion to and from Base64 is not necessary unless you need Base64 for some reason. It also isn't related to encrypting a string; it applies equally to anything you encrypt (or data of any kind for that matter).

Neither the Swift nor JNCryptor implementations generate or consume Base64 strings. Both of them accept and return bytes.

Base64 is generally used with RNCryptor when the ciphertext needs to be encoded into a text-only format like JSON, but it is not a general part of the encryption process.

**Comment by Sub-Zero-1** [comment]
JNCryptor returns base64 encoded String! As I know it is the same for Swift implentation.

    public static String JNencrypt(String password, String cleartext)
    {
        JNCryptor cryptor = new AES256JNCryptor();
        byte[]plaintext = cleartext.getBytes ();

        String a;
        try {
            byte[]ciphertext = cryptor.encryptData (plaintext, password.toCharArray ());
            a = Base64.encodeToString (ciphertext, Base64.NO_WRAP);
            return a;
        }

        catch (CryptorException e) {
            // Something went wrong
            e.printStackTrace ();
            return "0";
        }

    }

**Comment by rnapier** [comment]
That isn't JNCryptor. That looks like some kind of wrapper around JNCryptor that adds a Base64 encoding step (and does it in a somewhat dangerous way because `.getBytes()` is platform dependent). JNCryptor returns byte[]:

        byte[]ciphertext = cryptor.encryptData (plaintext, password.toCharArray ());

The Swift implementation definitely doesn't include a Base64-encoding step (I'm the maintainer of the Swift implementation).
