### ISSUE TITLE
Code Design Error - Encryption / Decryption Logic Flaw

### ISSUE THREAD

**Issue by CodeHeadEx** [RNCryptor/RNCryptor-cs#5]
Your code is a nice attempt to mimic RNCryptor, however it fails to be compatible. The library should work with byte data. Converting back and forth as you do to a string creates bloat and corrupts compatibility with RNCryptor. It also will fails on some string data.

Encrypt and Decrypt binary data only, let the end user be responsible for its translation for final display and use. Until you do this you will not be compatible with Napiers code. 

If you want assistance, I would be glad to join and share my code.

**Comment by rnapier** [comment]
I believe this is resolved in #8
