### ISSUE TITLE
Timing Attack Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [RNCryptor/RNCryptor-cs#9]
http://www.openwall.com/lists/oss-security/2016/01/24/10
- https://github.com/RNCryptor/RNCryptor-Spec/blob/04378bc27c604e97353badbead8c435698abe97a/RNCryptor-Spec-v3.md#consistent-time-equality-checking
- https://cryptocoding.net/index.php/Coding_rules#Compare_secret_strings_in_constant_time
- http://blog.ircmaxell.com/2014/11/its-all-about-time.html

Problematic code: https://github.com/RNCryptor/RNCryptor-cs/blob/8941882247c575bad558cd80c4f1dc04df82a019/RNCryptor/Decryptor.cs#L96-L110

**Comment by curtisdf** [comment]
Thanks again @paragonie-scott.  As with C++, C# is also not really my area of expertise.  Pull requests are welcome. Thanks!

**Comment by paragonie-scott** [comment]
https://github.com/paragonie-scott/cryptsharp/commit/16383e4ef275fe380e7a33a4f4cf25f78a128f30

Feel free to cannibalize that, but I'll send a PR if you can't get to it before me. :)
